modLoader = "javafml"

loaderVersion = "[35]"

showAsResourcePack = false

[[mods]]
	modId = "betterSlabs"
	version = "1.0"
	displayName = "Better Slabs"
	description = "Vertical slabs, double slabs, more slabs!"

	[[dependencies.betterSlabs]]
		modId = "forge"
		mandatory = true
		versionRange = "[35]"
		ordering = "NONE"
		side = "BOTH"

	[[dependencies.betterSlabs]]
		modId = "minecraft"
		mandatory = true
		versionRange = "[1.16.4]"
		ordering = "NONE"
		side = "BOTH"